server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /bgg-api/ {
        proxy_pass http://bgg-proxy:3001/;
        proxy_set_header Host bgg-proxy;
        add_header Access-Control-Allow-Origin "*";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/html text/css application/javascript application/json application/xml;
}